### ISSUE TITLE
Alert when there are new plugin versions

### ISSUE THREAD

**Issue by gdombiak** [gdombiak/OctoPod#198]
Would be nice not having to go to OctoPrint's console to find out that there are new plugin versions ready to be installed. This ticket is to research if this is possible

**Comment by jollino** [comment]
Just a little UX thing here... I had to look at the code to figure out what Ignore and Dismiss do, as it's not immediately obvious. Since we can't update plugins from the app (which makes sense, it may disrupt prints and so on), wouldn't a single button to acknowledge the message on the app be acceptable? It would essentially be a "preview" of the reminder that the user would get from the web version.
Of course I may have completely misunderstood the whole thing. :D

**Comment by gdombiak** [comment]
Both buttons do something different. I was not able to come up with a better word. They did not pass the test of my wife either. :(

Dismiss = Close window and do not alert for a day (I think)
Ignore = Never alert again for this update. If a new plugin update appears then display again alert

Let me know if you have a suggestion for better words.

Grazie,
Gaston

**Comment by jollino** [comment]
Maybe "Got it" and "Remind me later"? :-)
Or perhaps "Acknowledge" and "Snooze"…
