### ISSUE TITLE
iPad & iOS 13.2.3 Seems to induce weird Portrait/Landscape behaviour on Video Stream

### ISSUE THREAD

**Issue by ericd1949** [gdombiak/OctoPod#233]
This a great App, I've used it for a few weeks now on an iPad4 with iOS 10.3.3 connected to my Octoprint vers. 1.3.12, I carry it around the house whilst printing and can instantly change stuff.

Brilliant!!

Black Friday sales came and a I got an iPad 7th gen, iOS 13.2.3, and on this iPad the Video feed window positioning is weird. Both of my iPads have the same Octopod settings and the iPad portrait/landscape lock is off for both of them.

Here's a sequence of events on the newer iPad that illustrates the "interesting" behaviour:
**Turn on app in landscape
    Panel with no video feed window, top line is the grey bar with "PRINT JOB"
** Now turn iPad to portrait
    Panel with video feed window appears at the top, about 7cm across
    (smaller than the equivalent on the iPad 4 who's video is the full screen's width)
** Tap video window
    Full screen landscape video, iPad is still in portrait position.
** Turn iPad to landscape position
    Now still have landscape video, iPad in landscape position
** Turn iPad to portrait position
    Full screen, side to side, portrait video
** Tap video window
    Small video window & panel - display is portrait, iPad is portrait

There is no sequence that will get a landscape panel with a video feed window.

Full disclosure: up until now I haven't lived in iPad Land very much, I've spent most of my tablet existence in the Wild West that is Android Land.

Thanks very much for your App,
Cheers,
Eric

**Comment by gdombiak** [comment]
Hi Eric,

Whenever I have time, I'll try to use the simulator to see what you are seeing with your iPad. Would it be possible for you to post an image of what you are seeing? That might save me some time.

Thanks,
Gaston

**Comment by ericd1949** [comment]
Will do Gaston, tomorrow, screenshots of the vital moments will head your way, I'm sure iOS will make it easy for me :-)

Cheers,
Eric

On 3 December 2019 20:03:04 GMT+00:00, Gaston Dombiak <notifications@github.com> wrote:
>Hi Eric,
>
>Whenever I have time, I'll try to use the simulator to see what you are
>seeing with your iPad. Would it be possible for you to post an image of
>what you are seeing? That might save me some time.
>
>Thanks,
>Gaston
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gdombiak/OctoPod/issues/233#issuecomment-561333430

WahWay-ing on my sofa - somewhere ....... 😉

**Comment by gdombiak** [comment]
haha. iOS (or iPad OS now) makes it easy. https://support.apple.com/sl-si/HT200289

**Comment by ericd1949** [comment]
Wow, that was fun, iPad mail client, where are my files ?

So, with a bit of luck I’ll attach the screenshot of the landscape screenshot with no video window, and also the portrait screen with a very small video window.





Hope this helps,

Cheers,
Eric

**Comment by jollino** [comment]
@ericd1949 , you can attach files on iPad's mail client by doing this: https://support.apple.com/guide/ipad/add-attachments-ipadcf744d81/ipados (or perhaps just use the github web page? not sure as I have no iPad)

**Comment by ericd1949** [comment]
Thanks for your help, just for now, I've emailed them to myself and pasting them in. Such fun :-)

So, that seems to have worked; first the landscape screenshot with no video window, and then the portrait screen with a very small video window (iPad4 working beautifully in shot).

<img width="1080" alt="Lanscape_No_Video" src="https://user-images.githubusercontent.com/24812455/70152430-1f5fac00-16a5-11ea-9b89-b4f2b472ac7d.png">

<img width="810" alt="Portrait_Small_Video" src="https://user-images.githubusercontent.com/24812455/70152466-2dadc800-16a5-11ea-9e2b-c57f21aab509.png">

**Comment by ericd1949** [comment]
Oh dear I didn't mean to close this, sorry so clumsy of me.

**Comment by ericd1949** [comment]
Does my OctoPod (now v5.9) on my iPad 7th gen, iOS 13.2.3 think it has the display characteristics of an iPhone?

I persuaded my friend to load OctoPod on her iPhone 6 running 12.4.3

And the behaviour it exhibited was precisely the same as I detailed above; exactly as you would expect given it's more confined screen. In other words, my iPad7 is behaving the same as an iPhone with regards to portrait/landscape orientation changes, etc.

Oh dear, but I can't resist speculating in an area I have no knowledge of, but, has whatever the signalling protocol the OS uses to talk to Apps vis-a-vis iPad/iPhone identification, changed in 13.2.3?

Cheers,
Eric

**Comment by gdombiak** [comment]
Hi Eric,

Two words: Good guess!

OctoPod offers the same user experience on both iPhone and iPad. Depending on screen size of the iphone/ipad, it will decide how big should the image of the webcam be. For unknown screen sizes it defaults to some small value.

I wonder if that is your case. Could you tell me which screen size your iPad has? I think it is a 9.7 inches with a resolution of 1536x2048. I can check wether OctoPod knows how to render it or not.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Might be better to know the iPad model. I need to know the screen height. I expect it to be 1024 for a 9.7 inches screen. Maybe this is the problem why you see such a small image

**Comment by jollino** [comment]
I cannot say anything about the size of the feed shown on an iPad as I cannot test it, however it may be somewhat related to #118: maybe the video 'thing' has a maximum size that works for the iPhone 11/XR (which I believe is the biggest phone in terms of pixels), but then falls short on the iPad. It's been literally years since I did any iOS development so I'm not really sure how it all works nowadays. I in my days we used Objective-C, not Swift, and even autolayout was a new thing. :)

Regarding the original issue, I noticed a similar oddity on iPhone too:

1. Phone in portrait mode, video above as expected
2. Rotate to landscape, video disappears (as expected, I suppose, though I wouldn't mind a split view if at all possible...)
3. Back to portrait, tap the video feed, full screen video in landscape (with two grey bars on the sides in my case, as the screen is longer than 16:9 on the 11; same as #118 probably)
4. Rotate to landscape, video remains the same or rotates 180° depending on the side
5. Rotate to portait, video is straight but tiny, with giant grey bars above and below; even odder, the status bar is a different shade of grey than both the ones above and below the video, and even differ from my color scheme settings!

I'm not entirely sure what we should expect in this case, maybe just prevent the full-screen video feed from rotating to portrait mode?

https://www.youtube.com/watch?v=hYcgCu3AKvA

**Comment by gdombiak** [comment]
Thanks @jollino for the video. That helps. I'm not sure what is the suggestion here for improvement though. Is it about the shade of grey of point 5?

On the iPad, when you do point 2 you still see the video on top since there is space for it. On smaller screens I just hide the video.

**Comment by ericd1949** [comment]
Sorry for delay, nipped out for a beer.

This is a, so called by Apple, iPad (7th generation)
Model Number MW772B/A

and according to them it has a:
Retina display
10.2-inch (diagonal) LED-backlit Multi-Touch display with IPS technology
2160x1620-pixel resolution at 264 pixels per inch (ppi)

Wasn't the 9.7 inch" last" years model, and this is "this years, 2019" model.

Let me know if I can help.
Cheers,
Eric

**Comment by jollino** [comment]
> Thanks @jollino for the video. That helps. I'm not sure what is the suggestion here for improvement though. Is it about the shade of grey of point 5?

Um if anything I'd probably prevent the full-screen video from showing up in portrait mode, since it's effectively the same size as the main view, plus you can only get there by tapping into landscape and then rotating, so it feels a little weird from a user's standpoint.
I would do this:
a) When in full-screen video mode, allow the video to rotate to the other horizontal direction (like it already does) but disable portrait mode
b) When in normal mode, go to full-screen video mode when the phone is rotated (in addition to tapping). Showing normal mode in landscape on a phone doesn't really make much of a difference, except maybe for the temperature graph.

Just my humble two cents of course!

**Comment by gdombiak** [comment]
@ericd1949,

I was able to reproduce. Will fix and submit a new Beta version tonight (if possible). Are you in the beta testers group? If not send me an email to gdombiak at gmail if you would like to be part of it.

Daniele, will get back to you once done with Eric's issue.

Thanks,
Gaston

**Comment by gdombiak** [comment]
Fixed. This is 16:9 aspect ratio example
![Screen Shot 2019-12-15 at 2 14 28 PM](https://user-images.githubusercontent.com/1791267/70870216-4770ca00-1f45-11ea-9339-b98d6d3ccd3b.png)

And here 4:3
![Screen Shot 2019-12-15 at 2 14 33 PM](https://user-images.githubusercontent.com/1791267/70870222-59eb0380-1f45-11ea-88b6-070b5b6e1584.png)

Will now test the other new ipad models of 2019. Had no idea they changed resolutions. :)

**Comment by jollino** [comment]
No rush Gaston! I just mentioned it here with no intention of intruding — I hadn’t noticed it until I tried to reproduce Eric’s steps, as I seldom use the full screen view myself :)

-- 
Daniele Nicolucci (via iPhone)
Translation and other linguistic services at https://www.nicolucci.eu/
