### ISSUE TITLE
I am loving the AppleTV app!

### ISSUE THREAD

**Issue by jessearmstrong** [gdombiak/OctoPod#285]
No issue, I just didn't see another way to let you know that the AppleTV app is incredible and I love it. Now I wish I could see all my printers on my phone/ipad too. Thank you for improving my life with your apps.

**Comment by gdombiak** [comment]
Thanks @jessearmstrong for taking your time to write this. It's curious what you posted since I started to have the exact same need the moment I started to use the Apple TV app. I've been thinking how to design the UI so that we can have a nice dashboard of all printers both in the iPhone and iPad. It won't have camera but only running data with maybe a quick control for each printer. I don't think that rendering cameras of multiple printers will sit nice with iphone/ipad CPU and battery.

**Comment by gdombiak** [comment]
Filed https://github.com/gdombiak/OctoPod/issues/286 :)
