### ISSUE TITLE
System Commands don`t work

### ISSUE THREAD

**Issue by TempuzFugit** [gdombiak/OctoPod#533]
Hello, 
since the last update the System Commands don`t work. In OctoPrint all works well.

**Comment by gdombiak** [comment]
Thanks @TempuzFugit for reporting this issue. It is [now fixed](https://github.com/gdombiak/OctoPod/issues/532) and will be released soon. Will see if there is anything else important to fix and will push new version out soon. In the meantime, make sure that the **action** of the system command does not include % or ?. Once the fix is out you can put whatever you want in the action and will still work.

Regards,
Gaston

**Comment by TempuzFugit** [comment]
Works perfect. Thanks 👍
