### ISSUE TITLE
No camera feed when there is an extra space at the beginning

### ISSUE THREAD

**Issue by patduppat** [gdombiak/OctoPod#577]
Octoprint run on my computer with win 10.
Cam work end on the PC
However, the application does not show the video. I also have the same video problem if I am with another pc on the same home network

**Comment by gdombiak** [comment]
Hi @patduppat ,

What is the error that OctoPod displays? That should help troubleshoot the problem.

Gaston

**Comment by tenumars** [comment]
I have the same error, it is unsupported url. It works with other apps and the spaghetti detective. URL is /webcam/?action=stream I don't see anything wrong, and it works with other apps just fine.

**Comment by gdombiak** [comment]
Hi @tenumars,

Could you do the following and share results:
1. Check if there is an empty space before the beginning of /webcam... If there is one, try removing it and see if it works. I could fix this in next release if that is your case
2. Share a screenshot of the error you see in OctoPod? Also try clicking on the error message so that Safari opens up and share a screenshot of this as well

Thanks,
Gaston

**Comment by tenumars** [comment]
Yup, there was a space. Thanks! That fixed it!

**Comment by gdombiak** [comment]
Excellent! Thanks for confirming that. I will fix this for the next release so others do not have to manually remove any extra space.

Thanks,
Gaston

**Comment by tenumars** [comment]
I believe it was actually caused by me, because I needed to remove the space in the octoprint ui, not the octopod one.
